
modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU AGPL 3.0"
[[mods]] #mandatory
modId = "atomsweep" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "AtomSweep" #mandatory
authors = "cnlimiter" #optional
description = '''

'''
[[dependencies.atomsweep]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.atomsweep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side="BOTH"
