modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU AGPL 3.0"
[[mods]] #mandatory
modId = "atomsweep" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "AtomSweep" #mandatory
authors = "cnlimiter" #optional
description = '''

'''
[[dependencies.atomsweep]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"

